image: Visual Studio 2017

configuration: Release

before_build:
  - dotnet restore

environment:
  base_version: '1.0.1'
  version_suffix: ''

version: $(base_version).{build}$(version_suffix)

dotnet_csproj:
  patch: true
  file: 'uiowa.DelimitedDataHelper\*.csproj'
  version: '$(base_version)$(version_suffix)'
  assembly_version: '$(base_version)'
  file_version: '$(base_version).{build}'

build:
  parallel: true
  verbosity: minimal

test_script:
  - cd uiowa.DelimitedDataHelper.Tests
  - dotnet xunit --fx-version 2.1.0
  - cd ..\..

artifacts:
  - path: uiowa.DelimitedDataHelper\bin\%configuration%\*.nupkg

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: 1hZBCJrj4Gf9JsmiB3ZFoj5skbSFPmMgkGZhQxExHNHQg0jvg1prGWCWvGyXkDR+
  artifact: /.*\.nupkg/