language: csharp
mono:
  - latest
solution: uiowa.DelimitedDataHelper.sln
mono: none
dotnet: 2.1.401
script:
 - dotnet restore
 - cd ./uiowa.DelimitedDataHelper && dotnet pack -c=Release
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
#   on:
#     branch: master